language: python
python:
  - "2.7"

script:
  - which python
  - python setup.py install

after_success:
 - bash <(curl -s https://scripts.scantist.com/ci-travis-jar.sh)
after_success:
- bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
